In [2]:
!unzip -q 1.zip
!ls
%cd Mini_torch
!ls


from numba import cuda
print(cuda.is_available())

!ls minitorch

unzip:  cannot find or open 1.zip, 1.zip.zip or 1.zip.ZIP.
images		    project		    requirements.txt  tests
minitorch	    README.md		    setup.cfg	      Раздeл_3.ipynb
minitorch.egg-info  requirements.extra.txt  setup.py
[Errno 2] No such file or directory: 'Mini_torch'
/content/Mini_torch
images		    project		    requirements.txt  tests
minitorch	    README.md		    setup.cfg	      Раздeл_3.ipynb
minitorch.egg-info  requirements.extra.txt  setup.py
True
autodiff.py   fast_ops.py  operators.py		scalar.py	     testing.py
cuda_conv.py  __init__.py  optim.py		tensor_data.py
cuda_ops.py   module.py    __pycache__		tensor_functions.py
datasets.py   modules.py   scalar_functions.py	tensor_ops.py
fast_conv.py  nn.py	   scalar_modules.py	tensor.py


In [4]:
import minitorch
from minitorch.cuda_conv import conv1d, conv2d
import warnings

warnings.filterwarnings("ignore", category=Warning, module="numba")
warnings.filterwarnings("ignore", category=Warning, module="numba_cuda")

backend = minitorch.TensorBackend(minitorch.CudaOps)

x1 = minitorch.tensor(
    [[[1.0, 2.0, 3.0, 4.0]]],
    backend=backend,
)

w1 = minitorch.tensor(
    [[[1.0, 1.0]]],
    backend=backend,
)

y1 = conv1d(x1, w1)
print("conv1d result:")
print(y1)
print("conv1d shape:", y1.shape)


x2 = minitorch.tensor(
    [[[[1.0, 2.0, 3.0, 4.0],
       [5.0, 6.0, 7.0, 8.0],
       [9.0, 10.0, 11.0, 12.0],
       [13.0, 14.0, 15.0, 16.0]]]],
    backend=backend,
)

w2 = minitorch.tensor(
    [[[[1.0, 1.0],
       [1.0, 1.0]]]],
    backend=backend,
)

y2 = conv2d(x2, w2)
print("conv2d result:")
print(y2)
print("conv2d shape:", y2.shape)


x = minitorch.rand((2, 3, 8), backend=backend)
w = minitorch.rand((4, 3, 3), backend=backend)

x.requires_grad_(True)
w.requires_grad_(True)

out = conv1d(x, w)
loss = out.sum()
loss.backward()

print("conv1d forward shape:", out.shape)
print("x grad shape:", x.grad.shape)
print("w grad shape:", w.grad.shape)

x2 = minitorch.rand((2, 3, 8, 8), backend=backend)
w2 = minitorch.rand((4, 3, 3, 3), backend=backend)

x2.requires_grad_(True)
w2.requires_grad_(True)

out2 = conv2d(x2, w2)
loss2 = out2.sum()
loss2.backward()

print("conv2d forward shape:", out2.shape)
print("x2 grad shape:", x2.grad.shape)
print("w2 grad shape:", w2.grad.shape)

conv1d result:

[
	[
		[3.00 5.00 7.00 4.00]]]
conv1d shape: (1, 1, 4)
conv2d result:

[
	[
		[
			[14.00 18.00 22.00 12.00]
			[30.00 34.00 38.00 20.00]
			[46.00 50.00 54.00 28.00]
			[27.00 29.00 31.00 16.00]]]]
conv2d shape: (1, 1, 4, 4)
conv1d forward shape: (2, 4, 8)
x grad shape: (2, 3, 8)
w grad shape: (4, 3, 3)
conv2d forward shape: (2, 4, 8, 8)
x2 grad shape: (2, 3, 8, 8)
w2 grad shape: (4, 3, 3, 3)
